#// <>==<>==<> ItemJoin's Settings, by RockinChaos  <>==<>==<> //#
#// See the Documentations page for a more in-depth tutorial; https://www.spigotmc.org/wiki/itemjoin/ //#
#// For per-world support this best works with Multiverse-Inventories! http://dev.bukkit.org/bukkit-plugins/multiverse-inventories //#
config-Version: 6

 #// English is currently the only support language at the moment! //#
Language: 'English'
CheckForUpdates: true
Log-Coloration: true
Items-Permissions: true
Debugging-Mode: false


#// Global Settings for ItemJoin. //#
Prevent-Pickups: false
HeldItem-Slot: None


#// Global Clear Items for ItemJoin. //#
#// Set Clear-Items to ItemJoin or to All, ItemJoin clears only the ItemJoin items and All will clear all items. //#
Clear-Items: ItemJoin
Clear-On-Join: false
Clear-On-WorldChanged: false
AllowOPBypass: false
CreativeBypass: false


#// Global Commands for ItemJoin on join, these commands are executed by console. //#
enabled-global-commands: false
enabled-worlds: world, world_nether
global-commands:
  - 'itemjoin get <item> <player>'


#// These are optional dependencies, only change these if you are looking to use them in conjunction with ItemJoin, changing the values will require a server restart. //#
Vault: false
PlaceholderAPI: false
Multiverse-Core: false
Multiverse-Inventories: false
PerWorldInventory: false
PerWorldPlugins: false
xInventories: false
TokenEnchant: false
HeadDatabase: false
WorldGuard: false
MyWorlds: false
AuthMe: false