name: ItemJoin
main: me.RockinChaos.itemjoin.ItemJoin
version: 2.3
author: RockinChaos
commands:
   itemjoin:
      description: Displays some options.
      usage: |
          /itemjoin
   itemjoin help:
      description: Displays some options.
      usage: |
          /itemjoin help
   itemjoin reload:
      description: Reloads the ItemJoin config.yml.
      usage: |
          /itemjoin reload
   itemjoin updates:
      description: Checks for updates.
      usage: |
          /itemjoin updates
   itemjoin loaded:
      description: Checks what worlds are loaded.
      usage: |
          /itemjoin loaded
   itemjoin permissions:
      description: Checks what permissions you have.
      usage: |
          /itemjoin permissions
   itemjoin get:
      description: Gives you an itemjoin item.
      usage: |
          /itemjoin get
   itemjoin world:
      description: Checks what world you are in. For (debugging).
      usage: |
          /itemjoin world
   ij:
      description: Displays some options.
      usage: |
          /ij
   ij help:
      description: Displays help options.
      usage: |
          /ij help
   ij reload:
      description: Reloads the ItemJoin config.yml
      usage: |
          /ij reload
   ij updates:
      description: Checks for updates.
      usage: |
          /ij updates
   ij loaded:
      description: Checks what worlds are loaded.
      usage: |
          /ij loaded
   ij permissions:
      description: Checks what permissions you have.
      usage: |
          /ij permissions
   ij get:
      description: Gives you an itemjoin item.
      usage: |
          /ij get
   ij world:
      description: Checks what world you are in. For (debugging).
      usage: |
          /ij world
          
permissions:
   itemjoin.*:
      description: Allows use of all commands.
      default: false
   itemjoin.permissions:
      description: Use of the /itemjoin prermissions commands.
      default: true
   itemjoin.use:
      description: Currently allows use of basic commands.
      default: op
   itemjoin.reload:
      description: Allows use of reload command.
      default: op
   itemjoin.updates:
      description: Use of the /itemjoin update command.
      default: op
   itemjoin.get:
      description: Use of the /itemjoin get command.
      default: op
   itemjoin.get.others:
      description: Use of the /itemjoin get for player command.
      default: op
   itemjoin.WorldName.#:
      description: Replace # with slot number and WorldName with name of world to recieve that item.
      default: false
   itemjoin.WorldName.*:
      description: Gives permission to get all items from specified world.
      default: false