name: ItemJoin
main: me.xsilverslayerx.itemjoin.ItemJoin
version: 2.2
author: XSilverSlayerX
commands:
   itemjoin:
      description: Displays some options
      usage: |
          /itemjoin
   itemjoin help:
      description: Displays some options
      usage: |
          /itemjoin help
   itemjoin reload:
      description: Reloads the ItemJoin config.yml
      usage: |
          /itemjoin reload
   itemjoin updates:
      description: Checks for updates
      usage: |
          /itemjoin updates
   ij:
      description: Displays some options
      usage: |
          /ij
   ij help:
      description: Displays help options
      usage: |
          /ij help
   ij reload:
      description: Reloads the ItemJoin config.yml
      usage: |
          /ij reload
   ij updates:
      description: Checks for updates
      usage: |
          /ij updates
          
permissions:
   itemjoin.use:
      description: Currently allows use of base commands
      default: op
   itemjoin.reload:
      description: Allows use of reload command. You need itemjoin.use with this permission to use reload command.
      default: op
   itemjoin.updates:
      description: Use of the /itemjoin update command.
      default: op
   itemjoin.*:
      description: Allows use of all commands.
      default: false
   itemjoin.WorldName.#:
      description: Replace # with slot number and WorldName with name of world to recieve that item.
      default: false
   itemjoin.WorldName.*:
      description: Gives permission to get all items from specified world.
      default: false