name: ItemJoin
main: me.RockinChaos.itemjoin.ItemJoin
version: 3.1
author: RockinChaos
commands:
   itemjoin:
      description: Displays some options.
      usage: |
          /itemjoin
   itemjoin help:
      description: Displays some options.
      usage: |
          /itemjoin help
   itemjoin reload:
      description: Reloads the ItemJoin config.yml.
      usage: |
          /itemjoin reload
   itemjoin updates:
      description: Checks for updates.
      usage: |
          /itemjoin updates
   itemjoin loaded:
      description: Checks what worlds are loaded.
      usage: |
          /itemjoin loaded
   itemjoin permissions:
      description: Checks what permissions you have.
      usage: |
          /itemjoin permissions
   itemjoin permissions 2:
      description: Checks what permissions you have.
      usage: |
          /itemjoin permissions 2
   itemjoin get <item>:
      description: Gives you an itemjoin item.
      usage: |
          /itemjoin get <item>
   itemjoin get <item> <player>:
      description: Gives that player an itemjoin item.
      usage: |
          /itemjoin get <item> <player>
   itemjoin world:
      description: Checks what world you are in. For (debugging).
      usage: |
          /itemjoin world
   itemjoin list:
      description: Checks what items you can get each what world.
      usage: |
          /itemjoin list
   ij:
      description: Displays some options.
      usage: |
          /ij
   ij help:
      description: Displays help options.
      usage: |
          /ij help
   ij reload:
      description: Reloads the ItemJoin config.yml
      usage: |
          /ij reload
   ij updates:
      description: Checks for updates.
      usage: |
          /ij updates
   ij loaded:
      description: Checks what worlds are loaded.
      usage: |
          /ij loaded
   ij permissions:
      description: Checks what permissions you have.
      usage: |
          /ij permissions
   ij permissions 2:
      description: Checks what permissions you have.
      usage: |
          /ij permissions 2
   ij get <item>:
      description: Gives you an itemjoin item.
      usage: |
          /ij get <item>
   ij get <item> <player>:
      description: Gives that player an itemjoin item.
      usage: |
          /ij get <item> <player>
   ij world:
      description: Checks what world you are in. For (debugging).
      usage: |
          /ij world
   ij list:
      description: Checks what items you can get each what world.
      usage: |
          /ij list
          
permissions:
   itemjoin.*:
      description: Allows use of all commands.
      default: false
   itemjoin.permissions:
      description: Use of the /itemjoin permissions commands.
      default: true
   itemjoin.use:
      description: Currently allows use of basic commands.
      default: op
   itemjoin.reload:
      description: Allows use of reload command.
      default: op
   itemjoin.updates:
      description: Use of the /itemjoin update command.
      default: op
   itemjoin.get:
      description: Use of the /itemjoin get <item> command.
      default: op
   itemjoin.get.others:
      description: Use of the /itemjoin get <item> <others> for player command.
      default: op
   itemjoin.list:
      description: Use of the /itemjoin list command.
      default: op
   itemjoin.WorldName.Name:
      description: Replace Name with the name of the specified item and WorldName with name of world to receive that item.
      default: false
   itemjoin.WorldName.*:
      description: Gives permission to get all items from specified world.
      default: false